sudo: required
services:
  - docker

before_install:
  - docker build -t mannj99/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true mannj99/react-test npm test

after_success:
  - docker build -t mannj99/multi-client ./client
  - docker build -t mannj99/multi-nginx ./nginx
  - docker build -t mannj99/multi-server ./server
  - docker build -t mannj99/multi-worker ./worker
  # Log In to docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  # Take these production ready images and push them to docker hub
  - docker push mannj99/multi-client
  - docker push mannj99/multi-nginx
  - docker push mannj99/multi-server
  - docker push mannj99/multi-worker

deploy:
  provider: elasticbeanstalk
  region: 'us-east-1'
  app: 'multi-docker'
  env: 'multi-docker-env'
  bucket_name: 'elasticbeanstalk-us-east-1-713666903937' 
  bucket_path: 'docker-multi'
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
